### ISSUE TITLE
error: privilege check fail 

### ISSUE THREAD

**Issue by ngaut** [ngaut/faketikv#62]
There is a error while i am preparing sysbench data.

tidb log:

"INSERT INTO sbtest1(k, c, pad) VALUES(14947141, '25942538382-19136984219-03861106288-00576970577-24361311750-47763414368-95178035149-83010171818-94394022182-87430334962', '24869299864-61603159965-38945076374-93777316936-50603219421'),(17545198, '81442642794-60382140656-21233555113-58218451272-77109691109-52814287258-89440595380-15163701954-67119216642-43657914142', '24695893933-87471404260-82711175980-59472878298-42570363340'),(15086200, '50221825239-02409764394-42446296722-69370192650-86436920893-85303191233-28256048222-04772872232-95794565156-15075269747', '05086997714-95097113848-83724660080-80357869664-75330299471'),(15137543, '65789183760-12848267816-07060840582-63213013982-02522273917-24637380381-28838778300-85018632103-02165466915-05385930764', '21814949874-44174266203-35420832017-32226301537-92609885410'),(14968754, '33228637159-82746513466-46082047040-52794191177-26669469944-04204687379-09046206646-53573703440-96153431980-67158704032', '97913131593-64960156309-97561504476-56948131188-42597317139'),(15075178, '03368274570-55350378630-46248612450-75075447369-07022025604-68767005599-53220779465-25810639785-89014302611-54509261924', '99845394751-78058218736-57962540933-32604856768-33986950361'),(15001481, '66603183228-61466811240-11430085314-35408672269-57781845116-78008740514-23898105495-88328529221-98508124765-84880427463', '09990774584-19231381853-31659921542-80299963918-50651055923'),(15116754, '68467023426-31773815428-35642348859-05304725239-97985872096-94955178075-43798513426-34301445307-70171762665-48131041859', '39938311449-94586015486-98894138469-93369481986-28174115680'),(15052370, '10289294954-56634955769-95468129144-08111915664-17205037012-11944634561-23902737161-06120887916-03085184108-70366891026', '46832298697-56528320326-63946001979-84556253988-48414140497'),(13173103, '07808623488-37494438529-68911101408-65363181328-23295325189-55770754116-93488292778-92554158790-54359946342-25095094013', '17089085009-56376586045-09234257250-51520035242-83530051065'),(15018422, '65874745031-59894551247-84102470725-18673753548-68140362227-83701094413-50646338769-04077965417-50973078597-71928423289', '34747416711-11257577034-01168384928-98471901351-99679325341'),(15135426, '54826917340-81643664845-21025768793-62303450818-36816204091-61712155967-82956993568-77563968558-12219448499-28883230850', '18058955963-89167631334-64235806479-66208235083-08769055107'),(14978944, '44851766122-91800362170-06708311531-55473388114-96891145540-92457994050-58087050558-66019874438-68779540220-37355423707', '53986375378-96477923848-88510077062-42719080048-91461529042'),(15060061, '10988706069-47734912624-48802843488-92196119291-48788266084-82133788557-15423510118-92506461721-11243795397-04604440472', '47331977007-28355576295-20897049439-53874396831-63935693427'),(15028799, '19604005726-07919770045-98811397774-57830225528-70964553689-58186730194-12857850067-73427305289-62395733770-58988071928', '03139346131-68675015580-76536579821-27819894476-36474540175'),(15076427, '39944082574-94205332313-11017896328-56416004299-63606324792-08465974875-50721995044-99446775127-61652722929-97428107215', '72650417728-76600872741-75898884843-32973569499-04141454205'),(14983607, '70808081401-23107603448-32179536288-75379925487-24522202316-43019653721-97879630877-81725689913-92603905729-62839443825', '56217309847-32941981176-93715183847-62509676499-13611858626'),(15064966, '66899214066-76230744367-60784889735-15838961985-93688473907-02603433152-17996095728-50995360787-66123509673-93954391064', '75150680880-37899821798-15231898535-10222643760-25627465724'),(15110017, '95496239493-57619321091-96548297340-90082026065-56401021560-33177452711-33439288304-77992884274-05838973161-15571979998', '52408365398-14311354607-93268359479-06012850725-80187305298'),(15033672, '26704635751-33895996446-78478356895-13631098690-59711214978-81444225220-38439575626-40843743030-19499305676-20421342416', '70286985010-04405373975-93857133445-27725838956-10699676966'),(14952796, '85230707594-52126585305-89659319998-61006944379-19946243091-30407077239-52427799210-97072746003-91330573852(len: 524232)"
/home/pingcap/projects/src/github.com/pingcap/tidb/plan/optimizer.go:77: privilege check fail
/home/pingcap/projects/src/github.com/pingcap/tidb/executor/compiler.go:50:
/home/pingcap/projects/src/github.com/pingcap/tidb/session/session.go:837:
/home/pingcap/projects/src/github.com/pingcap/tidb/session/session.go:757:
/home/pingcap/projects/src/github.com/pingcap/tidb/server/conn.go:867:
2018/07/11 11:56:48.919 server.go:312: [info] [con:3] close connection
2018/07/11 11:56:52.321 session.go:836: [warning] [con:11] compile error:
privilege check fail
select count(*) from sbtest1
2018/07/11 11:56:52.321 conn.go:488: [warning] [con:11] dispatch error:
id:11, addr:192.168.198.98:52358 status:2, collation:utf8_general_ci, user:root
"select count(*) from sbtest1"
/home/pingcap/projects/src/github.com/pingcap/tidb/plan/optimizer.go:77: privilege check fail
/home/pingcap/projects/src/github.com/pingcap/tidb/executor/compiler.go:50:
/home/pingcap/projects/src/github.com/pingcap/tidb/session/session.go:837:
/home/pingcap/projects/src/github.com/pingcap/tidb/session/session.go:757:
/home/pingcap/projects/src/github.com/pingcap/tidb/server/conn.go:867:

**Comment by coocood** [comment]
This probably caused by this change 
https://github.com/coocood/badger/blob/master/iterator.go#L467

A simple way to reproduce the data corruption issue.

1. I cleaned the data
2. start pd/faketikv/tidb-server
3. stop tidb-server and faketikv
4. restart faketikv and tidb-server

Then tidb-server failed to start.

Without that change, the cluster can restart normally.
